services:
  database-university-library:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db-data-university-library:/var/lib/postgresql/data/

volumes:
  db-data-university-library:
